{{- if .Values.MONITORING_ENABLED }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.SERVICE_NAME }}-service-monitor
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: {{ .Values.SERVICE_NAME }}
    app: open-telemetry-collector
spec:
  endpoints:
  - interval: 30s
    port: {{ .Values.SERVICE_MONITOR_PORT_NAME }}
    path: /metrics
    scheme: http
  - interval: 30s
    port: self-telemetry
    path: /metrics
    scheme: http
  selector:
    matchLabels:
      app: open-telemetry-collector
{{- end }}
